### ISSUE TITLE
very slow 

### ISSUE THREAD

**Issue by Hirdyanshbhalla** [EnginAcikgoz/instavon#1]
it will take so much time to first check proxies and then bruteforcing them on instagram, is there any fast script ???

**Comment by EnginAcikgoz** [comment]
Please increase threads count and try again. It still slow?

**Comment by Hirdyanshbhalla** [comment]
ya i think its not working properly

**Comment by EnginAcikgoz** [comment]
Maybe you are using slow proxy servers? Please try again with different proxy list.
----
And can you send me more information?
